---
- name: Ensure that the liquidprompt package is installed
  tags: liquidprompt
  homebrew:
    name: liquidprompt
    state: present
  register: liquidprompt_homebrew

- name: Attempting to overlay liquidprompt configurations
  tags: liquidprompt
  template:
    src: liquidpromptrc.j2
    dest: "{{ liquidprompt_dest }}/.liquidpromptrc"
    owner: "{{ liquidprompt_owner }}"
    group: "{{ liquidprompt_group }}"
    mode: 0644
  when: liquidprompt_homebrew is success
...
