---
- name: Ensure that the liquidprompt package is installed
  tags: liquidprompt
  homebrew:
    name: liquidprompt
    state: present

- name: Attempting to overlay liquidprompt configurations
  tags: liquidprompt
  template:
    src: liquidpromptrc.j2
    dest: "{{ [liquidprompt_dest, '.liquidpromptrc'] | join('/') }}"
    owner: "{{ liquidprompt_owner }}"
    group: "{{ liquidprompt_group }}"
    mode: 0644
  when:
    - liquidprompt_dest is defined
    - liquidprompt_owner is defined
    - liquidprompt_group is defined
...
